language: python

sudo: required

cache: pip

services: postgresql

python:
  - 2.7
  - 3.4

install: 
  - pip install -r requirements.txt --quiet

env:
  - DJANGO_SETTINGS_MODULE=bsm.settings

before_script:
  - createdb -O postgres travisci
  - python manage.py migrate --noinput

script: 
  - flake8
  - python manage.py test