language: python

cache: pip

services: postgresql

python:
  - "2.7"
  - "3.4"

install: 
  - pip install -r requirements.txt --quiet
  - python manage.py migrate --noinput

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script: 
  - python manage.py test