language: python

sudo: required

cache: pip

services: postgresql

python:
  - "2.7"
  - "3.4"

install: 
  - pip install -r requirements.txt --quiet
  - python manage.py migrate --noinput

before_script:
  - createuser --createdb --no-superuser --no-createrole bsm_web
  - createdb -O bsm_web bsm_web

script: 
  - flake8
  - python manage.py test