# NOTE: Saucelabs's free open source option only allows for 4 conncurrent jobs on Travis CI

language: python
sudo: required
cache: pip

addons:
  sauce_connect: true

services: postgresql

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt --quiet

env:
  global:
    # Env vars specified here are available to every build
    - DJANGO_SETTINGS_MODULE=bsm.settings
    - BROWSER_VERSION=latest
    - BASE_URL=http://localhost:8000

    # Encrypted values for SAUCE_USERNAME and SAUCE_ACCESS_KEY
    - secure: "L5BjG8/6TSVEfNloYDRrgAncUkTSkEYx8d8GtbmV7lko079p1eSOGAiJ7aJwnVeuYaoBdxwO6hmoxePfoyL4wFuPja5Eh5pVIhHxGjS0JZe+EjI9Fo7EIq1pOR/OiI/+zL9uSNWPmJ7zCjq77DbMdwVP/3RMWxHBm11RNuhRk7deLZwfNzEerrw/fSpuhtNRmBL1ASgQrivlmoPjd5ylcPFg25MU9l+WlElObJH5nJqYUP+AG7RNGaaauuMh+Hl7+Fkf3C6C+wm+OZy2DF2Pr7m+zP7B6rrhqaU0Oz0Mm+TiETt07n8xj4IxV6uduyX/RqS8BbNUDZRcubJ6Rzv6iY+DPfpTa7tQFtzIk0S3G3lw712rx/ycIBIWAqJCPlt2zhC2m5yHQIAualM7GHPGBQ8/CVmlWQp+ypywJOcrH8KTukpUQTGld1S96tiXirgtJbV3S0qtfTkwtY9ey2grcvowux+TH7wdfLk7EnY2w5LGIbEz6yn0PgMPzLQ0d8UUU+1kSwIhQI4TuuO5nNBO9QgIdtosT4Ss5maX16fX3BUzcvDrdBnIpnzeDrPIDZsPgFUyVD9OHxnUDxjzsx5C4eekJdwEF6pV+EprRk5APCnxL2k/Eujsc0t4zdE/6F4ukt7y6fpCeqP+XwpfRDNUnBFGJMLCw21NmtBEKYGIA6E="
    - secure: "hHGeMxUqH/Qsi3G9Cd90btkTxb+rNLdvzSSwcdZlBrj0aejovMqKg07Ls1mtRq9zMbmtr897qBDjEH4k/aiD6mDYxk2bjLeT702Y4fgyjdp8YYjA2PAjUBr1DYj7wGnLn8XpWbZtymamkePrNF9BQEAhtoBlybfgcnyCkBpPBGKNnjp4P+aG9WKvdxAisxDnsbYY0h6fPyns09X6aoKnhltfWyGGvKKijCpBcwB68sbr2kLDhgomKoVBmDySjRhmuz/80FDB12Se6PGteZiG1T4hTvSlIidC+svnjKCnmfoD3MGrL7hxO8LSpqUSkZNyJTLxelTB4UscKOklnwfSj4w4tj+H60ghXLixr6Rx+St4sw3L0zTH4nnta/N2PvgRieuFG/7Rv3gNtiC9x9y6YPGjyOTPmEkVHf0j0M5WWVRWunTo0l3l49x/tgN61TxymDUsVooaXGMREee5Tzl1MF97n6ty41CrKfEO6HP805OusWHTZdC6GjmFaK7A0ghRqLN8EDEy3UtvYeLGz9ZHcKpIid5zlJFwIYAGnKpo7YqeBlvnn10RKsCIE5k3ov83uO0d1ok/f11bs8sDltKUlmwig9EB+WjKakYRjvHnmSDCtlmjD8gXcFs3scLHItwNhsTxXYmv4bpPUGlLiA8Lq47r59o0cl7hZ/B2BwcIzzM="

  matrix:
    # Each row within `matrix` will spawn a separate Travis build with the env
    # vars specified in said row while inheriting all vars defined in `global`
    - BROWSER_NAME=Firefox  OPERATING_SYSTEM="OS X 10.11"
    - BROWSER_NAME=Firefox  OPERATING_SYSTEM="Linux"
    - BROWSER_NAME=Chrome  OPERATING_SYSTEM="OS X 10.11"
    - BROWSER_NAME=Chrome  OPERATING_SYSTEM="Linux"
    - BROWSER_NAME=Safari  OPERATING_SYSTEM="OS X 10.11"

before_script:
  - createdb -O postgres travisci
  - python manage.py migrate --noinput

script:
  # Any error will cause travis to exit early and report a failure.
  - set -e

  - echo 'travis_fold:start:flake8'
  - flake8 --exclude=migrations,settings.py .
  - echo 'travis_fold:end:flake8'

  - echo 'travis_fold:start:django_tests'
  - python manage.py test
  - echo 'travis_fold:end:django_tests'

  - echo 'travis_fold:start:selenium'
  # NOTE: Redirect runserver output since it's polluting logs
  - python manage.py runserver > /dev/null 2>&1 &
  - pushd selenium_tests
  # NOTE: Sauce Connect needs SAUCE_USERNAME and SAUCE_ACCESS_KEY
  # (https://docs.travis-ci.com/user/sauce-connect/),
  # while Pytest looks for SAUCELABS_USERNAME and SAUCELABS_API_KEY
  # (http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#sauce-labs).
  # This has been recognized as a point of confusion, but there is no plan to change anything.
  # https://github.com/pytest-dev/pytest-selenium/issues/53
  - export SAUCELABS_USERNAME=$SAUCE_USERNAME SAUCELABS_API_KEY=$SAUCE_ACCESS_KEY
  - printenv | sort | grep SAUCE | perl -pne 's/=(...).+/=$1.../' # Debug helper
  - pytest -k selenium_ --driver SauceLabs --capability browserName $BROWSER_NAME --capability version $BROWSER_VERSION --capability platform "$OPERATING_SYSTEM" --capability tunnelIdentifier $TRAVIS_JOB_NUMBER -r fE
  - popd
  - echo 'travis_fold:end:selenium'
