language: python

sudo: required

cache: pip

services: postgresql

python:
  - "2.7"
  - "3.4"

install: 
  - pip install -r requirements.txt --quiet
  - python manage.py migrate --noinput

before_script:
  - psql -c 'create database travisci;' -U postgres

script: 
  - flake8
  - python manage.py test