# NOTE: Saucelabs's free open source option only allows for 4 conncurrent jobs on Travis CI

language: python
sudo: required
cache: pip

addons:
  sauce_connect: true

services: postgresql

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt --quiet

env:
  global:
    # Env vars specified here are available to every build
    - DJANGO_SETTINGS_MODULE=bsm.settings
    - BROWSER_VERSION=latest
    - BASE_URL=http://localhost:8000

  matrix:
    # Each row within `matrix` will spawn a separate Travis build with the env
    # vars specified in said row while inheriting all vars defined in `global`
    - BROWSER_NAME=Firefox  OPERATING_SYSTEM="OS X 10.11"
    - BROWSER_NAME=Firefox  OPERATING_SYSTEM="Linux"
    - BROWSER_NAME=Chrome  OPERATING_SYSTEM="OS X 10.11"
    - BROWSER_NAME=Chrome  OPERATING_SYSTEM="Linux"
    - BROWSER_NAME=Safari  OPERATING_SYSTEM="OS X 10.11"

before_script:
  - createdb -O postgres travisci
  - python manage.py migrate --noinput

script:
  # Any error will cause travis to exit early and report a failure.
  - set -e

  - echo 'travis_fold:start:flake8'
  - flake8 --exclude=migrations,settings.py .
  - echo 'travis_fold:end:flake8'

  - echo 'travis_fold:start:django_tests'
  - python manage.py test
  - echo 'travis_fold:end:django_tests'

  - echo 'travis_fold:start:selenium'
  # NOTE: Redirect runserver output since it's polluting logs
  - python manage.py runserver > /dev/null 2>&1 &
  - pushd selenium_tests
  # NOTE: Sauce Connect needs SAUCE_USERNAME and SAUCE_ACCESS_KEY
  # (https://docs.travis-ci.com/user/sauce-connect/),
  # while Pytest looks for SAUCELABS_USERNAME and SAUCELABS_API_KEY
  # (http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#sauce-labs).
  # This has been recognized as a point of confusion, but there is no plan to change anything.
  # https://github.com/pytest-dev/pytest-selenium/issues/53
  - export SAUCELABS_USERNAME=$SAUCE_USERNAME SAUCELABS_API_KEY=$SAUCE_ACCESS_KEY
  - printenv | sort | grep SAUCE | perl -pne 's/=(...).+/=$1.../' # Debug helper
  - pytest -k selenium_ --driver SauceLabs --capability browserName $BROWSER_NAME --capability version $BROWSER_VERSION --capability platform "$OPERATING_SYSTEM" --capability tunnelIdentifier $TRAVIS_JOB_NUMBER -r fE
  - popd
  - echo 'travis_fold:end:selenium'
