# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 23:36
from __future__ import unicode_literals

import bsct.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumber',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CaseNumber',
                'verbose_name_plural': 'CaseNumber',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('alignment_status', models.CharField(choices=[('UNKNOWN', 'Alignment status Unknown'), ('NEEDED', 'Realignment Needed'), ('IN_PROGRESS', 'Realignment In Progress'), ('COMPLETED', 'Realignment Complete')], default='UNKNOWN', max_length=20)),
                ('annotation', models.BooleanField(default=False)),
                ('bulk_or_single_cell', models.CharField(choices=[('BULK', 'bulk'), ('SINGLE_CELL', 'single cell')], max_length=20)),
                ('cnv_calling_status', models.CharField(choices=[('UNKNOWN', 'CNV calling status Unknown'), ('NEEDED', 'CNV calling Needed'), ('IN_PROGRESS', 'CNV calling In Progress'), ('COMPLETED', 'CNV calling Complete')], default='UNKNOWN', max_length=20)),
                ('coverage', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('path_to_bam', models.CharField(blank=True, max_length=250, null=True)),
                ('path_to_raw_read', models.CharField(blank=True, max_length=250, null=True)),
                ('path_to_vcf', models.CharField(blank=True, max_length=250, null=True)),
                ('quality_check_status', models.CharField(choices=[('UNKNOWN', 'QC status Unknown'), ('NEEDED', 'QC Needed'), ('IN_PROGRESS', 'QC In Progress'), ('COMPLETED', 'QC Complete')], default='UNKNOWN', max_length=20)),
                ('variant_calling', models.CharField(blank=True, max_length=250, null=True)),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.CaseNumber')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.Diagnosis')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
        migrations.CreateModel(
            name='SequencingCenter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'SequencingCenter',
                'verbose_name_plural': 'SequencingCenter',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
        migrations.AddField(
            model_name='sample',
            name='sequenced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.SequencingCenter'),
        ),
        migrations.AddField(
            model_name='casenumber',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.Project'),
        ),
    ]
