# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4,
                                          editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4,
                                          editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('case_number', models.IntegerField()),
                ('bulk', models.BooleanField(default=False)),
                ('single_cell', models.BooleanField(default=False)),
                ('quality_check_status', models.BooleanField(default=False)),
                ('annotation', models.BooleanField(default=False)),
                ('path_to_bam', models.CharField(max_length=250)),
                ('path_to_raw_read', models.CharField(max_length=250)),
                ('path_to_vcf', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=250)),
                ('coverage', models.CharField(max_length=250)),
                ('variant_calling', models.CharField(max_length=250)),
                ('cnv_calling', models.CharField(max_length=250)),
                ('alignment_status', models.CharField(choices=[('UNKNOWN', 'Alignment status Unknown'), ('NEEDED', 'Realignment Needed'), (
                    'IN_PROGRESS', 'Realignment In Progress'), ('COMPLETED', 'Realignment Complete')], default='UNKNOWN', max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequencingCenter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4,
                                          editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sequencing_center',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.SequencingCenter'),
        ),
    ]
