# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AlterModelOptions(
            name='sequencingcenter',
            options={'verbose_name': 'SequencingCenter', 'verbose_name_plural': 'SequencingCenters'},
        ),
        migrations.AlterField(
            model_name='project',
            name='sequencing_center',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.SequencingCenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bsm_samples.Project'),
            preserve_default=False,
        ),
    ]
