# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 00:41
from __future__ import unicode_literals

import bsct.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
            bases=(models.Model, bsct.models.BSCTModelMixin),
        ),
    ]
